# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(419, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEditCost = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditCost.setCursorPosition(0)
        self.lineEditCost.setObjectName("lineEditCost")
        self.gridLayout.addWidget(self.lineEditCost, 9, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditName.setText("")
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 6, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 0, 1, 1)
        self.lineEditValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditValue.setText("")
        self.lineEditValue.setObjectName("lineEditValue")
        self.gridLayout.addWidget(self.lineEditValue, 10, 0, 1, 1)
        self.lineEditDegree = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditDegree.setObjectName("lineEditDegree")
        self.gridLayout.addWidget(self.lineEditDegree, 5, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 12, 0, 1, 1)
        self.lineEditTaste = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditTaste.setObjectName("lineEditTaste")
        self.gridLayout.addWidget(self.lineEditTaste, 7, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактор БД"))
        self.label.setText(_translate("Form", "Элементы БД о кофе"))
        self.lineEditCost.setPlaceholderText(_translate("Form", "Цена"))
        self.lineEditName.setPlaceholderText(_translate("Form", "Название сорта"))
        self.lineEditValue.setPlaceholderText(_translate("Form", "Объем упаковки"))
        self.lineEditDegree.setPlaceholderText(_translate("Form", "Степень обжарки"))
        self.pushButton_2.setText(_translate("Form", "Редактирование БД"))
        self.lineEditTaste.setPlaceholderText(_translate("Form", "Описание вкуса"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
